development:
  adapter: mysql2
  database: igram
  username: root
  password:
  socket: /private/var/mysql/mysql.sock
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: igram
  username: root
  password:
  socket: /private/var/mysql/mysql.sock
  host: localhost
  encoding: utf8
